import { renderPdfPageToBase64 } from '../pdf.js';
import { chooseBestCandidates, detectSimpleFormula, analyzeCandidateAmbiguity, P4_SCHEMA } from './core.js';
export { exportP4ExcelWorkbook } from '../p4-pdf-excel-intelligence.js';

function saveBlob(buf,name){
  if(typeof globalThis.__HNL_CAPTURE_XLSX__==='function') return globalThis.__HNL_CAPTURE_XLSX__(buf,name);
  if(typeof document==='undefined') return {ok:true,buffer:buf,fileName:name};
  const blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),a=document.createElement('a');
  a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1200);return {ok:true,fileName:name};
}
function header(row,color='FF17365D'){row.font={bold:true,color:{argb:'FFFFFFFF'}};row.fill={type:'pattern',pattern:'solid',fgColor:{argb:color}};row.alignment={vertical:'middle',wrapText:true};}
function style(ws){ws.eachRow(r=>r.alignment={vertical:'top',wrapText:true});ws.views=[{state:'frozen',ySplit:1}];}
function safe(s='HNL_PDF_Excel'){return String(s).replace(/[^A-Za-z0-9._-]+/g,'_').slice(0,80)||'HNL_PDF_Excel';}
function b64ToBuffer(b64=''){const bin=atob(b64),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return u;}
function candidateState(c){return c?.source==='native-text'?'ỨNG VIÊN PDF':'CẦN RÀ SOÁT';}

export async function exportPdfExcelWorkbook({docs=[],result={},question='',imageMode='relevant',includeText=true,includeFormulas=true,sourceSha='',validateOnly=false}={}){
  const mod=await import('exceljs'),ExcelJS=mod.default||mod,wb=new ExcelJS.Workbook();
  wb.creator='HNL Pile Standards AI';wb.subject='PDF/Ảnh → Excel Intelligence';wb.calcProperties={fullCalcOnLoad:true,forceFullCalc:true,calcMode:'auto'};wb.customProperties={hnlSchema:P4_SCHEMA,sourceSha:String(sourceSha||result.sourceSha||'')};
  const overview=wb.addWorksheet('00_TONG_QUAN');overview.columns=[{width:28},{width:95}];overview.addRow(['HNL PDF → EXCEL INTELLIGENCE','P4 SHADOW / REVIEW']);header(overview.getRow(1));
  overview.addRows([['Câu hỏi',question||''],['Biến cần tìm',(result.variables||[]).join(', ')],['Số ứng viên',(result.candidates||[]).length],['Nguyên tắc','PDF.js Native được ưu tiên để đọc; OCR/Vision chỉ là evidence CẦN RÀ SOÁT. Không tự đưa vào Calculation Engine.'],['Công thức Excel','Luồng quét toàn tài liệu chỉ ghi preview. Formula thật chỉ được tạo ở exporter P4 VERIFIED khi đủ provenance + mapping biến.'],['Source SHA',sourceSha||result.sourceSha||'']]);style(overview);
  const chosen=chooseBestCandidates(result),ambiguity=analyzeCandidateAmbiguity(result);
  const inp=wb.addWorksheet('01_THAM_SO');inp.columns=[{width:16},{width:20},{width:14},{width:20},{width:16},{width:24},{width:65}];inp.addRow(['Tham số','Giá trị','Đơn vị','Trạng thái','Trang','Engine','Nguồn / ngữ cảnh']);header(inp.getRow(1),'FF548235');
  for(const v of result.variables||[]){const c=chosen.find(x=>x.variable===v);const r=inp.addRow([v,c?.value??c?.valueRaw??'',c?.unit||'',candidateState(c),c?.page||'',c?.engine||'',c?.context||'']);r.getCell(2).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFF2CC'}};}style(inp);
  const cand=wb.addWorksheet('02_UNG_VIEN');cand.columns=[{width:12},{width:18},{width:14},{width:14},{width:28},{width:24},{width:20},{width:20},{width:70}];cand.addRow(['Tham số','Giá trị','Đơn vị','Trang','Tài liệu','Engine','Trạng thái','BBox','Ngữ cảnh']);header(cand.getRow(1),'FF8064A2');
  for(const c of result.candidates||[])cand.addRow([c.variable,c.value??c.valueRaw??'',c.unit||'',c.page||'',c.document||c.fileName||'',c.engine||'',candidateState(c),Array.isArray(c.bbox)?c.bbox.map(x=>Number(x).toFixed(4)).join(', '):'',c.context||'']);style(cand);
  const prov=wb.addWorksheet('03_NGUON');prov.columns=[{width:26},{width:24},{width:12},{width:22},{width:24},{width:20},{width:64},{width:44}];prov.addRow(['Tài liệu','Fingerprint','Trang','BBox','Engine','Trạng thái','Provenance','Source SHA']);header(prov.getRow(1),'FF7F6000');
  for(const c of result.candidates||[])prov.addRow([c.document||c.fileName||'',c.fingerprint||'',c.page||'',Array.isArray(c.bbox)?JSON.stringify(c.bbox):'',c.engine||'',candidateState(c),`${c.source||''}${c.promotionState?` · ${c.promotionState}`:''}`,sourceSha||result.sourceSha||'']);style(prov);
  if(includeText){const ws=wb.addWorksheet('04_TEXT_TRICH_XUAT');ws.columns=[{width:28},{width:10},{width:100}];ws.addRow(['Tài liệu','Trang','Text']);header(ws.getRow(1),'FF5B9BD5');for(const d of docs||[])for(const p of d.pages||[])if(String(p.text||'').trim())ws.addRow([d.standard||d.name||'',p.page||'',String(p.text||'').slice(0,30000)]);style(ws);}
  if(includeFormulas){const allText=(docs||[]).flatMap(d=>(d.pages||[]).map(p=>p.text||'')).join('\n'),formulas=detectSimpleFormula(allText,result.variables||[]),ws=wb.addWorksheet('05_CONG_THUC');ws.columns=[{width:14},{width:54},{width:54},{width:24},{width:70}];ws.addRow(['Kết quả','Biểu thức gốc','Excel preview','Trạng thái','Ghi chú']);header(ws.getRow(1),'FF4472C4');const rowByVar=new Map((result.variables||[]).map((v,i)=>[v,i+2]));for(const f of formulas){let preview=f.rhs.replace(/×/g,'*').replace(/\bx\b/g,'*');for(const [v,row] of rowByVar)preview=preview.replace(new RegExp(`\\b${v.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')}\\b`,'g'),`'01_THAM_SO'!B${row}`);ws.addRow([f.lhs,f.rhs,`=${preview}`,'CẦN RÀ SOÁT','Chỉ là preview dạng chữ; chưa VERIFIED nên không ghi formula thực thi.']);}style(ws);}
  const review=wb.addWorksheet('06_REVIEW');review.columns=[{width:16},{width:22},{width:90}];review.addRow(['Tham số','Loại','Yêu cầu rà soát']);header(review.getRow(1),'FFC65911');if(!ambiguity.length)review.addRow(['—','Thông tin','Không phát hiện xung đột ứng viên; vẫn cần xác nhận trước khi dùng thiết kế.']);for(const x of ambiguity)review.addRow([x.variable,x.type==='MULTIPLE_VALUES'?'Nhiều giá trị/ngữ cảnh':'Chưa tìm thấy',x.message]);style(review);
  if(imageMode!=='none'){const relevantPages=new Map();for(const c of chosen){if(c.page){const d=(docs||[]).find(x=>x.id===c.docId)||(docs||[]).find(x=>x.fingerprint===c.fingerprint);if(d)relevantPages.set(`${d.id}:${c.page}`,{doc:d,page:c.page});}}if(imageMode==='all'&&!relevantPages.size){for(const d of docs||[])for(const p of(d.pages||[]).slice(0,8))relevantPages.set(`${d.id}:${p.page}`,{doc:d,page:p.page});}if(relevantPages.size){const ws=wb.addWorksheet('07_MINH_HOA');ws.columns=[{width:28},{width:10},{width:85}];ws.addRow(['Tài liệu','Trang','Hình nguồn']);header(ws.getRow(1),'FF70AD47');let row=2,count=0;for(const {doc,page} of relevantPages.values()){if(count>=12)break;try{const image=await renderPdfPageToBase64(doc,page,1.15),id=wb.addImage({buffer:b64ToBuffer(image.data),extension:'jpeg'});ws.addRow([doc.standard||doc.name||'',page,'']);ws.addImage(id,{tl:{col:2,row:row-1},ext:{width:560,height:790}});ws.getRow(row).height=600;row++;count++;}catch(error){ws.addRow([doc.standard||doc.name||'',page,`Không render được: ${error?.message||error}`]);row++;}}style(ws);}}
  const buf=await wb.xlsx.writeBuffer();if(validateOnly)return{ok:true,workbook:wb,buffer:buf,ambiguity};return saveBlob(buf,`${safe((docs[0]?.standard||docs[0]?.name||'HNL')+'_PDF_EXCEL')}.xlsx`);
}
